name: 'Composite Action Example'
description: 'A composite action to checkout code and set up Node.js'
runs:
  using: 'composite'
  steps:
     - name: Checkout code
       uses: actions/checkout@v4
     - id: setup_python_relative_path
       run: |
         action_path=$(python -c "import os; print(os.path.relpath('${{ github.action_path }}', '${{ github.workspace }}'))")
         echo "action_path=${action_path}" >> "$GITHUB_OUTPUT"
       shell: bash

     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.10'
         cache: 'pip'
         cache-dependency-path: ${{ steps.setup_python_relative_path.outputs.action_path }}/requirements.txt
