name: 'Composite Action Example'
description: 'A composite action to checkout code and set up Node.js'
runs:
  using: 'composite'
  steps:
     - name: Checkout code
       uses: actions/checkout@v4
    
     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.10'
         cache: 'pip'
         cache-dependencies: |
            PyYAML>5,<7
            sr.comp>=1.4,<2
            sr.comp.scorer>=1.4,<2
