name: check hardcode path
on:
  workflow_dispatch:
jobs:
  "test":
    runs-on: macos-latest
    steps:
      - name: Set up Python
        uses: AttilaT/setup-python@patch-1
        with:
          python-version: 3.11
