name: python testing
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Python binaries from prebuilt package
        run: |
           echo "Install Python binaries from prebuilt package"
           sudo installer -pkg $PYTHON_PKG_NAME -target /
