
name: User Post Setup Tests with v3
on:
  workflow_dispatch:

env:
  PNPM_CACHE_FOLDER: .pnpm-store  # Make sure this is correctly defined

jobs:
  version_or_release:
    name: 'Version and open PR (or) release private packages'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    environment: 'Production - Private Packages'
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: pnpm/action-setup@v4
      
      - name: Create PNPM Cache Directory
        run: mkdir -p $PNPM_CACHE_FOLDER  # Ensure the cache directory exists

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'  # Use 'pnpm' to enable pnpm caching

      - name: Setup PNPM Store Config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Debug Cache Directory
        run: |
          echo "Contents of PNPM Cache Directory:"
          ls -la $PNPM_CACHE_FOLDER  # Verify the cache directory contents
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: List Node Modules
        run: |
          echo "Contents of Node Modules Directory:"
          ls -la node_modules  # Check the node_modules structure
