name: Release (Private Packages)
on:
  workflow_dispatch:
jobs:
  "test":
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12.5
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.5
      - name: Verify Python Version
        run: python --version
      
